### ISSUE TITLE
Undefined References

### ISSUE THREAD

**Issue by rstory1** [dpmcmlxxvi/SpatiaLiteCpp#8]
I've been working on adding this to a project I'm working on. I have added the files to my project and the library file. I'm using Qt and code completion is working for the SpatiaLite files, but when I go to compile I get errors for 'undefined reference to SpatiaLiteDb' or anything else I try to use from SpatiaLite.

Any pointers? Thanks in advance.

**Comment by rstory1** [comment]
Pretty sure I'm doing something stupid. I'm going to keep checking my linkages and whatever else may be wrong.

**Comment by dpmcmlxxvi** [comment]
OK. The only linkage problems would be from the 3rd party externals (`SpatiaLite`, `SQLite`, `SQLite++`). If they are not found they you'll get unresolved references. `SpatiaLiteDb` doesn't ring a bell and is likely part of `Spatialite`. I don't see any file called that in the `SpatiaLiteC++` repo.

Just adding the source files to your project would be the easiest way to build.
