### ISSUE TITLE
Problem binding blob to prepared statement

### ISSUE THREAD

**Issue by cellard0or** [dpmcmlxxvi/SpatiaLiteCpp#9]
Hey Daniel,

I am trying to use your SpatiaLiteC++ wrapper. So far it looks very convenient, thanks for that!

I am having trouble to do a certain thing, though: I fail to bind a geometry blob to a prepared statement. Unfortunately, the examples do not go into detail after creating the blob itself.

I am using this line from your examples:

BlobPtr pointZ(Point::makePoint(srid, x, y, &z));

My  code looks like this:

```
SQLite::Statement insertPoint(*db.getDatabase(),
                "INSERT INTO test "
                "(id, position)"
                "VALUES "
                "(NULL, ?);");

int srid = 4326;
double z = 75.4;
SpatiaLite::BlobPtr pointZ(SpatiaLite::Point::makePoint(srid, 40.5, 12.64, &z));

insertPoint.bind(1, pointZ.get(), pointZ->getSize());
```
The column I am inserting the Geometry into was created like this:
`SELECT AddGeometryColumn('test', 'position', 4326, 'POINTZ');`

When running this code I get the following error: "exception: test.position violates Geometry constraint [geom-type or SRID not allowed]".

This is the last thing that keeps me from working with Spatialite/C++ efficiently and I would be grateful if you can help me with that :)

**Comment by dpmcmlxxvi** [comment]
This looks like a Spatialite issue and not a an issue with the wrapper. However, if you can provide a link to a [mcve](https://stackoverflow.com/help/mcve) that I can compile and test, I can look into it.

**Comment by dpmcmlxxvi** [comment]
Have you verified that you do not see this issue when using Spatialite without the wrapper?

**Comment by cellard0or** [comment]
Yes. It works without the wrapper. I created a paste with the plain spatialite example, similar to the spatialiteCpp mcve: https://pastebin.com/m37NAe8S

I guess I am doing something wrong with the blob conversion or the binding.
Thanks again for your time and support!

**Comment by dpmcmlxxvi** [comment]
Your code looks fine. The only difference between the wrapper example and the non-wrapper example is the SQL string to create the point (line 26 vs line 31). Any reason they are different? If you found an answer to your issue I'll close the issue.
